[build.environment]
  NODE_VERSION = "14"

[build]
  publish = "dist"
  command = "npx playwright install && sudo npx playwright install-deps && yarn build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
